### ISSUE TITLE
你好，想请教一个打印的问题

### ISSUE THREAD

**Issue by fanrt** [tlzzu/SoDiaoEditor#49]
我现在换成版本4了，在使用打印时，按照demo中使用sde.seniorPrint({...})里面的内容并没有效果，是什么问题呢？

**Comment by fanrt** [comment]
问题发现了，要点击高级打印才会触发这个，但是高级打印点击没反应，git下来的代码点击也是没反应的

**Comment by tlzzu** [comment]
高级版打印目前在内部测试

**Comment by fanrt** [comment]
好的，谢谢了
