### ISSUE TITLE
打印是否能去掉[]

### ISSUE THREAD

**Issue by petezhanghong** [tlzzu/SoDiaoEditor#50]
你好 , 非常感谢你无私的为医疗信息化的贡献 , 我也采用你的编辑器 , 但我们在使用中 , 有一个需求不知道是否能实现 , 打印时候去掉控件[]

**Comment by tlzzu** [comment]
最近在忙着几家三甲医院的上线，这个早就实现了，目前没时间往github上整合

**Comment by petezhanghong** [comment]
很好 , 希望你有时间能尽快整合 , 期待你的更新
