### ISSUE TITLE
SDE v4 alpha版 远程数据问题

### ISSUE THREAD

**Issue by lurenj** [tlzzu/SoDiaoEditor#51]
麻烦问一下 ctrl_remote_handle，//ctrl远程数据异步请求，接收一个remote对象，返回处理后的remote对象本身？这里是直接写访问路径了？还是需要我们直接用ajax访问，获取，再返回啊？有点不清楚应该怎么配置！

**Comment by tlzzu** [comment]
因为remote中的url往往是相对地址，ctrl_remote_handle方法就是将remote.url修改为绝对地址，然后返回修改后的remote对象

**Comment by lurenj** [comment]
感谢，我突然发现了,这个是方法是用在控件中使用的！顺便问一下SDE v4有稳定版吗？现在这边版本的用着问题有点多啊！且不停的报“该功能尚在内部测试阶段“！

**Comment by tlzzu** [comment]
有
